theme = "gruvbox"

[editor]
mouse = false
shell = ["nu", "--stdin", "-l", "-c"]
auto-format = true
bufferline = "multiple"
soft-wrap.enable = true
popup-border = "all"

[editor.statusline]
center = ["version-control"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1 

[keys.insert]
"A-x" = "normal_mode"     # Maps Alt-X to enter normal mode
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

[keys.normal]
# Git
h.b = ":sh git blame -n %{buffer_name} -L %{cursor_line},%{cursor_line}"

# AI
space.space.a = "@:sh ai (r#'<C-r>.'#)<ret>"

# Elixir

space.space.c = ":sh mix compile"
space.space.t = ":sh zellij action new-pane  -f -- mix test %{buffer_name} --trace"
space.space.T = ":sh zellij action new-pane  -f -- mix test %{buffer_name}:%{cursor_line} --trace"
space.space.F = ":sh zellij action new-pane  -f -- mix test"
