[language-server.zls]
command = "zls"

[language-server.elixir]
command = "elixir-ls"

[language-server.refactorex]
command = "/Users/yurko/Code/refactorex/bin/start"
args = ["--stdio"]

[language-server.tailwind-heex]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.gleam-lsp]
command = "gleam"
args = ["lsp"]

[language-server.iwe]
command = "iwes"

[[language]]
name = "markdown"
language-servers = [ "iwe" ] # you might want more LSPs in here
auto-format = true

[[language]]
name = "gleam"
auto-format = true
language-servers = ["gleam-lsp"]
file-types = ["gleam"]

[[language]]
name = "rust"
auto-format = false

[[language]]
name = "elixir"
auto-format = true
language-servers = ["elixir", "refactorex"]
language-id = "phoenix-heex"

[[language]]
name = "heex"
language-id = "phoenix-heex"
language-servers = ["tailwind-heex", "elixir-ls"]
auto-format = true

[[language]]
name = "zig"
language-servers = [ "zls" ]

